apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: default
  name: hbase-master
spec:
  serviceName: "hbase-master"
  podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        component: hbase-master
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: hbase-master
          image: 10.254.0.50:5000/hbase:1.2.7 
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HBASE_SERVER_TYPE 
              value: master
            - name: ZOOKEEPER_SERVICE_LIST 
              value: zk-cs 
          ports:
            - containerPort: {{.port.1}}
            - containerPort: {{.port.2}}
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: {{.claim}}
              mountPath: {{.mount.path}}
            - name: {{.config.name}} 
              mountPath: {{.mount.path}}
              readOnly: true
              #subPath: {{.config.file}}
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: {{.claim}}
          persistentVolumeClaim:
            claimName: {{.claim.name}}
        - name: {{.config.name}} 
          configMap:
            name: {{.configmap.name}}
